# coding=utf-8
from django.shortcuts import render, redirect
from django.core.urlresolvers import reverse
from .forms import CustomerForm
from models import Group, CustomerUser

# Create your views here.
GROUPS = [
    [
        {
            "id": "1",
            "first_name": "Антон",
            "patronymic_name": "Павлович",
            "last_name": "Чехов",
            "club": "ДЮСШ-1",
            "criterio1": "3,1",
            "criterio2": "7",
            "criterio3": "23",
            "criterio4": "19",
            "criterio5": "44",
            "criterio6": "53",
            "criterio7": "23",
            "criterio8": "1,76",
            "criterio9": "9,12",
            "criterio10": "50",
            "criterio11": "89",
            "criterio12": "15",
            "criterio13": "35",
            "criterio14": "23",
            "criterio15": "45",
            "criterio16": "50",
            "criterio17": "30",
            "criterio18": "31",
            "criterio19": "12",
            "criterio20": "56",
        },
        {
            "id": "2",
            "first_name": "Максим",
            "patronymic_name": "Викторович",
            "last_name": "Петров",
            "club": "ДЮСШ-1",
            "criterio1": "3,2",
            "criterio2": "6",
            "criterio3": "20",
            "criterio4": "24",
            "criterio5": "40",
            "criterio6": "57",
            "criterio7": "25",
            "criterio8": "1,67",
            "criterio9": "9,1",
            "criterio10": "57",
            "criterio11": "91",
            "criterio12": "16",
            "criterio13": "31",
            "criterio14": "22",
            "criterio15": "48",
            "criterio16": "42",
            "criterio17": "38",
            "criterio18": "29",
            "criterio19": "8",
            "criterio20": "63",
        },
    ],
    [
        {
            "id": "1",
            "first_name": "Антон",
            "patronymic_name": "Михайлович",
            "last_name": "Руднев",
            "club": "ДЮСШ-1",
            "criterio1": "3,5",
            "criterio2": "6,5",
            "criterio3": "19",
            "criterio4": "31",
            "criterio5": "44",
            "criterio6": "55",
            "criterio7": "22",
            "criterio8": "1,65",
            "criterio9": "8,67",
            "criterio10": "50",
            "criterio11": "89",
            "criterio12": "17",
            "criterio13": "33",
            "criterio14": "26",
            "criterio15": "42",
            "criterio16": "53",
            "criterio17": "33",
            "criterio18": "33",
            "criterio19": "14",
            "criterio20": "58",
        },
        {
            "id": "2",
            "first_name": "Михаил",
            "patronymic_name": "Романович",
            "last_name": "Руков",
            "club": "ДЮСШ-1",
            "criterio1": "4,1",
            "criterio2": "5",
            "criterio3": "30",
            "criterio4": "24",
            "criterio5": "53",
            "criterio6": "52",
            "criterio7": "26",
            "criterio8": "1,89",
            "criterio9": "8,5",
            "criterio10": "52",
            "criterio11": "95",
            "criterio12": "12",
            "criterio13": "36",
            "criterio14": "24",
            "criterio15": "47",
            "criterio16": "57",
            "criterio17": "33",
            "criterio18": "35",
            "criterio19": "16",
            "criterio20": "53",
        },
    ],
    [
        {
            "id": "1",
            "first_name": "Владимир",
            "patronymic_name": "Владимирович",
            "last_name": "Воронцов",
            "club": "ДЮСШ-1",
            "criterio1": "3,9",
            "criterio2": "3",
            "criterio3": "25",
            "criterio4": "24",
            "criterio5": "47",
            "criterio6": "55",
            "criterio7": "24",
            "criterio8": "1,73",
            "criterio9": "9,2",
            "criterio10": "50",
            "criterio11": "89",
            "criterio12": "17",
            "criterio13": "32",
            "criterio14": "25",
            "criterio15": "47",
            "criterio16": "54",
            "criterio17": "36",
            "criterio18": "37",
            "criterio19": "13",
            "criterio20": "57",
        },
    ],
    [
        {
            "id": "1",
            "first_name": "Андрей",
            "patronymic_name": "Юрьевич",
            "last_name": "Камов",
            "club": "ДЮСШ-1",
            "criterio1": "3,5",
            "criterio2": "4",
            "criterio3": "27",
            "criterio4": "29",
            "criterio5": "50",
            "criterio6": "45",
            "criterio7": "22",
            "criterio8": "1,81",
            "criterio9": "9,92",
            "criterio10": "46",
            "criterio11": "88",
            "criterio12": "14",
            "criterio13": "36",
            "criterio14": "25",
            "criterio15": "45",
            "criterio16": "56",
            "criterio17": "32",
            "criterio18": "33",
            "criterio19": "16",
            "criterio20": "57",
        },
        {
            "id": "2",
            "first_name": "Ренат",
            "patronymic_name": "Сергеевич",
            "last_name": "Зимовин",
            "club": "ДЮСШ-1",
            "criterio1": "3,1",
            "criterio2": "4,7",
            "criterio3": "23",
            "criterio4": "18",
            "criterio5": "44",
            "criterio6": "43",
            "criterio7": "23",
            "criterio8": "1,76",
            "criterio9": "9,8",
            "criterio10": "50",
            "criterio11": "89",
            "criterio12": "15",
            "criterio13": "35",
            "criterio14": "23",
            "criterio15": "45",
            "criterio16": "50",
            "criterio17": "30",
            "criterio18": "31",
            "criterio19": "12",
            "criterio20": "56",
        },
        {
            "id": "3",
            "first_name": "Максим",
            "patronymic_name": "Валентинович",
            "last_name": "Сидоров",
            "club": "ДЮСШ-1",
            "criterio1": "4,2",
            "criterio2": "5,4",
            "criterio3": "28",
            "criterio4": "18",
            "criterio5": "48",
            "criterio6": "54",
            "criterio7": "26",
            "criterio8": "1,91",
            "criterio9": "9,5",
            "criterio10": "45",
            "criterio11": "94",
            "criterio12": "18",
            "criterio13": "36",
            "criterio14": "23",
            "criterio15": "43",
            "criterio16": "57",
            "criterio17": "33",
            "criterio18": "36",
            "criterio19": "18",
            "criterio20": "54",
        },
    ]
]
PLAYERS_INFO = [
    # {
    #     "id": "1",
    #     "first_name": "Михаил",
    #     "patronymic_name": "Евгеневич",
    #     "last_name": "Шорохов",
    #     "club": "Торпедо",
    #     "criterio1": "2,5",
    #     "criterio2": "5",
    #     "criterio3": "23",
    #     "criterio4": "23",
    #     "criterio5": "44",
    #     "criterio6": "30",
    #     "criterio7": "2",
    #     "criterio8": "1",
    #     "criterio9": "9,2",
    #     "criterio10": "75",
    #     "criterio11": "90",
    #     "criterio12": "22",
    #     "criterio13": "75",
    #     "criterio14": "19",
    #     "criterio15": "55",
    #     "criterio16": "60",
    #     "criterio17": "65",
    #     "criterio18": "31",
    #     "criterio19": "2",
    #     "criterio20": "56",
    # },
    # {
    #     "id": "3",
    #     "first_name": "Андрей",
    #     "patronymic_name": "Сергеевич",
    #     "last_name": "Иванов",
    #     "club": "Торпедо",
    #     "criterio1": "2,8",
    #     "criterio2": "4",
    #     "criterio3": "23",
    #     "criterio4": "16",
    #     "criterio5": "44",
    #     "criterio6": "25",
    #     "criterio7": "1",
    #     "criterio8": "0,8",
    #     "criterio9": "8,3",
    #     "criterio10": "50",
    #     "criterio11": "100",
    #     "criterio12": "22",
    #     "criterio13": "50",
    #     "criterio14": "23",
    #     "criterio15": "55",
    #     "criterio16": "70",
    #     "criterio17": "65",
    #     "criterio18": "31",
    #     "criterio19": "2",
    #     "criterio20": "56",
    # },
    {
        "id": "4",
        "first_name": "Антон",
        "patronymic_name": "Павлович",
        "last_name": "Чехов",
        "club": "ДЮСШ-1",
        "criterio1": "3,1",
        "criterio2": "7",
        "criterio3": "23",
        "criterio4": "19",
        "criterio5": "44",
        "criterio6": "53",
        "criterio7": "23",
        "criterio8": "1,76",
        "criterio9": "9,12",
        "criterio10": "50",
        "criterio11": "89",
        "criterio12": "15",
        "criterio13": "35",
        "criterio14": "23",
        "criterio15": "45",
        "criterio16": "50",
        "criterio17": "30",
        "criterio18": "31",
        "criterio19": "12",
        "criterio20": "56",
    },
    {
        "id": "5",
        "first_name": "Максим",
        "patronymic_name": "Викторович",
        "last_name": "Петров",
        "club": "ДЮСШ-1",
        "criterio1": "3,2",
        "criterio2": "6",
        "criterio3": "20",
        "criterio4": "24",
        "criterio5": "40",
        "criterio6": "57",
        "criterio7": "25",
        "criterio8": "1,67",
        "criterio9": "9,1",
        "criterio10": "57",
        "criterio11": "91",
        "criterio12": "16",
        "criterio13": "31",
        "criterio14": "22",
        "criterio15": "48",
        "criterio16": "42",
        "criterio17": "38",
        "criterio18": "29",
        "criterio19": "8",
        "criterio20": "63",
    },
    {
        "id": "6",
        "first_name": "Андрей",
        "patronymic_name": "Юрьевич",
        "last_name": "Камов",
        "club": "ДЮСШ-1",
        "criterio1": "3,5",
        "criterio2": "4",
        "criterio3": "27",
        "criterio4": "29",
        "criterio5": "50",
        "criterio6": "45",
        "criterio7": "22",
        "criterio8": "1,81",
        "criterio9": "9,92",
        "criterio10": "46",
        "criterio11": "88",
        "criterio12": "14",
        "criterio13": "36",
        "criterio14": "25",
        "criterio15": "45",
        "criterio16": "56",
        "criterio17": "32",
        "criterio18": "33",
        "criterio19": "16",
        "criterio20": "57",
    },
    {
        "id": "7",
        "first_name": "Антон",
        "patronymic_name": "Михайлович",
        "last_name": "Руднев",
        "club": "ДЮСШ-1",
        "criterio1": "3,5",
        "criterio2": "6,5",
        "criterio3": "19",
        "criterio4": "31",
        "criterio5": "44",
        "criterio6": "55",
        "criterio7": "22",
        "criterio8": "1,65",
        "criterio9": "8,67",
        "criterio10": "50",
        "criterio11": "89",
        "criterio12": "17",
        "criterio13": "33",
        "criterio14": "26",
        "criterio15": "42",
        "criterio16": "53",
        "criterio17": "33",
        "criterio18": "33",
        "criterio19": "14",
        "criterio20": "58",
    },
    {
        "id": "8",
        "first_name": "Михаил",
        "patronymic_name": "Романович",
        "last_name": "Руков",
        "club": "ДЮСШ-1",
        "criterio1": "4,1",
        "criterio2": "5",
        "criterio3": "30",
        "criterio4": "24",
        "criterio5": "53",
        "criterio6": "52",
        "criterio7": "26",
        "criterio8": "1,89",
        "criterio9": "8,5",
        "criterio10": "52",
        "criterio11": "95",
        "criterio12": "12",
        "criterio13": "36",
        "criterio14": "24",
        "criterio15": "47",
        "criterio16": "57",
        "criterio17": "33",
        "criterio18": "35",
        "criterio19": "16",
        "criterio20": "53",
    },
    {
        "id": "9",
        "first_name": "Ренат",
        "patronymic_name": "Сергеевич",
        "last_name": "Зимовин",
        "club": "ДЮСШ-1",
        "criterio1": "3,1",
        "criterio2": "4,7",
        "criterio3": "23",
        "criterio4": "18",
        "criterio5": "44",
        "criterio6": "43",
        "criterio7": "23",
        "criterio8": "1,76",
        "criterio9": "9,8",
        "criterio10": "50",
        "criterio11": "89",
        "criterio12": "15",
        "criterio13": "35",
        "criterio14": "23",
        "criterio15": "45",
        "criterio16": "50",
        "criterio17": "30",
        "criterio18": "31",
        "criterio19": "12",
        "criterio20": "56",
    },
    {
        "id": "10",
        "first_name": "Владимир",
        "patronymic_name": "Владимирович",
        "last_name": "Воронцов",
        "club": "ДЮСШ-1",
        "criterio1": "3,9",
        "criterio2": "3",
        "criterio3": "25",
        "criterio4": "24",
        "criterio5": "47",
        "criterio6": "55",
        "criterio7": "24",
        "criterio8": "1,73",
        "criterio9": "9,2",
        "criterio10": "50",
        "criterio11": "89",
        "criterio12": "17",
        "criterio13": "32",
        "criterio14": "25",
        "criterio15": "47",
        "criterio16": "54",
        "criterio17": "36",
        "criterio18": "37",
        "criterio19": "13",
        "criterio20": "57",
    },
    {
        "id": "11",
        "first_name": "Максим",
        "patronymic_name": "Валентинович",
        "last_name": "Сидоров",
        "club": "ДЮСШ-1",
        "criterio1": "4,2",
        "criterio2": "5,4",
        "criterio3": "28",
        "criterio4": "18",
        "criterio5": "48",
        "criterio6": "54",
        "criterio7": "26",
        "criterio8": "1,91",
        "criterio9": "9,5",
        "criterio10": "45",
        "criterio11": "94",
        "criterio12": "18",
        "criterio13": "36",
        "criterio14": "23",
        "criterio15": "43",
        "criterio16": "57",
        "criterio17": "33",
        "criterio18": "36",
        "criterio19": "18",
        "criterio20": "54",
    },

]

FORM_INFO = {
    "first_name": "Антон",
    "patronymic_name": "Павлович",
    "last_name": "Чехов",
    "club": "ДЮСШ-1",
    "group": "Низкий",
    "role": "--",
    "email": "mumu@vreke.net",
    "month_of_birth": "2",
    "day_of_birth": "10",
    "year_of_birth": "1985",
    "gender": "m",
    "login": "AntonGoD"
}


def main_page(request):
    return render(request, 'index.html', {"title": "Home", "players": PLAYERS_INFO})


def club_page(request):
    return render(request, 'club.html', {"title": "Club"})


def user_profile_page(request):
    form = CustomerForm(data=FORM_INFO)
    return render(request, 'profile.html', {"title": "Profile", "form": form})


def user_club_page(request):
    form = CustomerForm(data=FORM_INFO)
    return render(request, 'user_club.html', {"title": "Profile", "form": form})


def groups_page(request):
    try:
        groups = Group.objects.all()
    except Exception:
        redirect(reverse("home"))
    return render(request, 'groups.html', {"title": "Groups", "group1": GROUPS[0], "group2": GROUPS[1], "group3": GROUPS[2], "group4": GROUPS[3],})


def med_test_page(request):
    return render(request, 'medic-test.html', {"title": "Test"})


def sport_test_page(request):
    return render(request, 'sport-test.html', {"title": "Test"})


def psyho_test_page(request):
    return render(request, 'psyho-test.html', {"title": "Test"})


def develop_page(request):
    return render(request, 'contacts.html', {"title": "Contacts"})


def user_statistics(request):
    form = CustomerForm(data=FORM_INFO)
    return render(request, 'user_statistics.html', {"title": "Statistics", "form": form})


def user_settings_page(request):
    return render(request, 'settings.html', {"title": "Settings"})



def login(request):
    return render(request, 'login.html', {"title": "Login"})



def create_user(request):
    return render(request, 'registrate.html', {"title": "Registration"})



def change_password(request):
    return render(request, 'change_password.html', {"title": "Change_password"})